### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by MelBourbon** [asciidisco/plugin.video.telekom-sport#7]
Login failed with correct credentials on Kodi 18 Beta and recent Plugin

### Steps to Reproduce

* Install Plugin
* Change Login in settings and select OK
* Error Message occuring

### Installation

* I´m using the Kodinerds Repo

### Kodi

* v18

### Operating System

* Linux (Vero 4K)

**Comment by michl85** [comment]
The error seams to be caused by this:

`ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest...l-warnings
InsecureRequestWarning)` (taken from kodi.log)

**Comment by Spoil001** [comment]
The fix in: https://www.kodinerds.net/index.php/Thread/57586-Release-Telekom-Sport/?postID=480064#post480064
is working for me.

<pre>
Habs mir gerade mal angeschaut und die Lösung für das Login Problem gefunden:

Python-Quellcode: plugin.video.telekom-sport\resources\lib\Session.py
success = 'Sport' in soup.find('title').get_text()
ersetzen durch:

Python-Quellcode: plugin.video.telekom-sport\resources\lib\Session.py
success = 'sport' in soup.find('title').get_text().lower()
Einfach vorerst die Datei händisch abändern, bis das Addon geupdated wird (@asciidisco - bitte das Repository updaten).

Was ich noch gerade festgestellt hab - der Login mit der Telekom Kundennummer geht auch nicht mehr - man muss nun das @t-online Login verwenden.
</pre>
